export const cont = [
  {
    layout: "post",
    title: "팀프로젝트",
    subTitle: "반려동물 밀착생활 앱 Anilog",
    image: "img/callum-shaw-555357-unsplash.jpg",
    author: [""],
    name: "sw",
    date: "2021-10-14 ~ 2022-08-14",
    tags: "",
    to: "/anilog",
    excerpt: "",
    imgUri: "https://i.imgur.com/crq9IaE.png",
  },
  {
    layout: "post",
    title: "개인 프로젝트",
    subTitle: "개발자 커뮤니티 사이트 JDK",
    image: "img/callum-shaw-555357-unsplash.jpg",
    author: [""],
    name: "sw",
    date: "2020-07-29 ~ 2020-09-12",
    tags: "",
    to: "/jdkproject",
    excerpt: "",
    imgUri: "https://i.imgur.com/U61b97E.png",
  },
  {
    layout: "post",
    title: "개인프로젝트",
    subTitle: "To Do List",
    image: "img/callum-shaw-555357-unsplash.jpg",
    author: [""],
    name: "sw",
    date: "2021-09-02 ~ 2021-10-13",
    tags: "",
    to: "/todo",
    excerpt: "",
    imgUri: "https://i.imgur.com/TB7Lc9z.png",
  },
];
